FORMAT: 1A
HOST: https://fiveringsdb.com/

# FiveRingsDB

An API to access cards and decks data from https://fiveringsdb.com

# Group Cards

Resources related to cards.

## Card Collection [/cards]

### List All Cards [GET]

+ Response 200 (application/json)

        {
            "success": true,
            "size": 1,
            "records": [
                {
                    "clan": "unicorn",
                    "code": "border-rider",
                    "cost": 2,
                    "deck_limit": 3,
                    "glory": 1,
                    "keywords": [
                        "bushi",
                        "cavalry"
                    ],
                    "military": 2,
                    "name": "Border Rider",
                    "name_canonical": "border rider",
                    "pack_cards": [
                        {
                            "illustrator": "Charles Urbach",
                            "pack": {
                                "code": "core"
                            },
                            "position": 112,
                            "quantity": 1
                        }
                    ],
                    "political": 1,
                    "side": "dynasty",
                    "text": "<b>Action:</b> Ready this character.",
                    "text_canonical": "action: ready this character.",
                    "type": "character",
                    "unicity": false
                }
            ]
        }


