<?php

namespace AppBundle\Repository;

/**
 * CardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @author Alsciende <alsciende@icloud.com>
 */
class CardRepository extends \Doctrine\ORM\EntityRepository
{
}
