<?php

namespace AppBundle\Repository;

/**
 * ClanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * @author Alsciende <alsciende@icloud.com>
 */
class ClanRepository extends \Doctrine\ORM\EntityRepository
{
}
