<?php

namespace AppBundle\Repository;

/**
 * ElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * @author Alsciende <alsciende@icloud.com>
 */
class ElementRepository extends \Doctrine\ORM\EntityRepository
{
}
