<?php

namespace AppBundle\Repository;

/**
 * PackSlotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackSlotRepository extends \Doctrine\ORM\EntityRepository
{
}
